Chapter 3: Central limit theorem notebook
astroML/astroML-notebooks pull request #37
Opened 2022-06-29 21:00 UTC by aalvar23

2022-07-11 19:38 UTC, bsipocz requested changes
Please also add this to the chapter3/README.md file so the rendered notebook will be linked from the readme page and show up in the TOC.

2022-07-13 14:34 UTC, bsipocz commented on chapter3/README.md
> +astroml_chapter3_Univariate_Distribution_Functions
please use the name of the new notebook rather than duplicate the previous one. Thanks!

2022-07-13 14:37 UTC, bsipocz commented
Thanks @aalvar23! It looks all good to me (pending I fix the LaTeX rendering issue), but before merging I'll ask @stephenportillo to sign off on the content, too.

2022-07-13 17:10 UTC, stephenportillo commented
A couple text changes:
"for the practice of repeated measurements in order to improve the accuracy of the final result" -> "for the practice of repeating measurements to improve the accuracy of the final result"
"Our constraints of" -> "Our constraints on"

It would be nice to demonstrate the CLT on a second distribution to reinforce the fact that it works for arbitrary distributions. In particular, I think it would be useful to show it working on a distribution with fat tails (but still finite standard deviation), like the Laplace distribution.

2022-07-22 03:21 UTC, aalvar23 commented
I uploaded the bivariate and multivariate notebook to my forked repository and it's showing up on this pull request; I tried to open a new one, but it doesn't give me the option. I checked this last notebook with Stephen though if you wanted to merge both at the same time. If not, I can try to figure out something else.

2022-07-22 16:51 UTC, bsipocz commented
yes, it shows up as the PR is from your main branch rather than from separate feature branches.

But now having them both in this PR fine, I want to fix the LaTeX rendering issue before merging this, so merging them both at the same time will be fine.

2022-07-27 23:37 UTC, bsipocz commented
I've rebased this, so CI should pick up the fix for the LaTeX rendering.

2022-07-27 23:47 UTC, bsipocz commented
I've removed the commit that removes the outputs, I think I have told you that empty notebooks are better, but we may need to keep the outputs in (pending a decision in #39).

2022-07-27 23:48 UTC, bsipocz approved these changes

2022-07-27 23:48 UTC, merged

2022-07-27 23:48 UTC, bsipocz commented
Thanks @aalvar23!